export enum ScoreActionTypes {
  FETCH_SCORE_REQUEST = "@@SCORE/FETCH/SCORE_REQUEST",
  FETCH_SCORE_ERROR = "@@SCORE/FETCH/SCORE_ERROR",
  FETCH_SCORE_SUCCESS = "@@SCORE/FETCH/SCORE_SUCCESS",

  FETCH_BUYITEM_REQUEST = "@@SCORE/FETCH/BUYITEM_REQUEST",
  FETCH_BUYITEM_SUCCESS = "@@SCORE/FETCH/BUYITEM_SUCCESS",
}
